q03_1parti: recursive.h recursive.c q03_1parti.c
	gcc -lm -o q03_1parti recursive.c q03_1parti.c
exp03_1parti: recursive.h recursive.c exp03_1parti.c
	gcc -lm -o exp03_1parti recursive.c exp03_1parti.c
q03_2money: recursive.h recursive.c q03_2money.c
	gcc -lm -o q03_2money recursive.c q03_2money.c
exp03_2money: recursive.h recursive.c exp03_2money.c
	gcc -lm -o exp03_2money recursive.c exp03_2money.c
q04_1sq: recursive.h recursive.c q04_1sq.c
	gcc -lm -o q04_1sq recursive.c q04_1sq.c
q04_2dp: recursive.h recursive.c q04_2dp.c
	gcc -lm -o q04_2dp recursive.c q04_2dp.c
exp04_2dp: recursive.h recursive.c exp04_2dp.c
	gcc -lm -o exp04_2dp recursive.c exp04_2dp.c
q04_3memo: recursive.h recursive.c q04_3memo.c
	gcc -lm -o q04_3memo recursive.c q04_3memo.c
q05_1ct: recursive.h recursive.c q05_1ct.c
	gcc -lm -o q05_1ct recursive.c q05_1ct.c
